// Product data with your actual images
const products = [
    { 
        id: 1, 
        name: "Бархатная бумага Флок Красный", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/1. Бархатная бумага Флок Красный.jpg", 
        description: "Насыщенная красная бархатная бумага с эффектом флокирования. Идеально подходит для создания праздничных открыток и упаковки.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Красный"],
        status: "in-stock"
    },
    { 
        id: 2, 
        name: "Бархатная бумага Флок Синий", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/2. Бархатная бумага Флок Синий.jpg", 
        description: "Глубокий синий цвет с бархатистой текстурой флок. Отлично подходит для деловых приглашений и элегантной упаковки.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Синий"],
        status: "in-stock"
    },
    { 
        id: 3, 
        name: "Бархатная бумага Флок Зеленый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/3. Бархатная бумага Флок Зеленый.jpg", 
        description: "Изумрудный зеленый оттенок бархатной бумаги с текстурой флок. Прекрасный выбор для природных и эко-тематик.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Зеленый"],
        status: "in-stock"
    },
    { 
        id: 4, 
        name: "Бархатная бумага Флок Черный", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/4. Бархатная бумага Флок Черный.jpg", 
        description: "Классический черный цвет с эффектом бархатного флока. Создает элегантный и драматический эффект.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Черный"],
        status: "in-stock"
    },
    { 
        id: 5, 
        name: "Бархатная бумага Флок Белый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/5. Бархатная бумага Флок Белый.jpg", 
        description: "Чистый белый цвет с бархатной текстурой флок. Идеален для свадебной полиграфии и светлых проектов.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Белый"],
        status: "in-stock"
    },
    { 
        id: 6, 
        name: "Бархатная бумага Флок Золотой", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 580, 
        image: "images/products/6. Бархатная бумага Флок Золотой.jpg", 
        description: "Роскошный золотой флок с металлическим блеском. Создает праздничное настроение и добавляет шика.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Золотой"],
        status: "in-stock"
    },
    { 
        id: 7, 
        name: "Бархатная бумага Флок Серебряный", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 580, 
        image: "images/products/7. Бархатная бумага Флок Серебряный.jpg", 
        description: "Элегантный серебряный флок с холодным блеском. Подходит для современных и минималистичных дизайнов.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Серебряный"],
        status: "in-stock"
    },
    { 
        id: 8, 
        name: "Бархатная бумага Флок Бордовый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/8. Бархатная бумага Флок Бордовый.jpg", 
        description: "Глубокий бордовый оттенок с бархатной текстурой. Создает благородную и утонченную атмосферу.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Бордовый"],
        status: "in-stock"
    },
    { 
        id: 9, 
        name: "Бархатная бумага Флок Фиолетовый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/9. Бархатная бумага Флок Фиолетовый.jpg", 
        description: "Насыщенный фиолетовый цвет с эффектом флокирования. Подходит для творческих и нестандартных проектов.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Фиолетовый"],
        status: "in-stock"
    },
    { 
        id: 10, 
        name: "Бархатная бумага Флок Розовый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/10. Бархатная бумага Флок Розовый.jpg", 
        description: "Нежный розовый оттенок с бархатной текстурой. Идеален для женственных и романтичных проектов.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Розовый"],
        status: "in-stock"
    },
    { 
        id: 11, 
        name: "Бархатная бумага Флок Оранжевый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/11. Бархатная бумага Флок Оранжевый.jpg", 
        description: "Энергичный оранжевый цвет с текстурой флок. Добавляет яркости и жизнерадостности в проекты.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Оранжевый"],
        status: "in-stock"
    },
    { 
        id: 12, 
        name: "Бархатная бумага Флок Коричневый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/12. Бархатная бумага Флок Коричневый.jpg", 
        description: "Натуральный коричневый оттенок с бархатной текстурой. Создает теплую и уютную атмосферу.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Коричневый"],
        status: "in-stock"
    },
    { 
        id: 13, 
        name: "Бархатная бумага Флок Голубой", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/13. Бархатная бумага Флок Голубой.jpg", 
        description: "Нежный голубой оттенок с бархатной текстурой. Идеален для весенних и детских проектов.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Голубой"],
        status: "in-stock"
    },
    { 
        id: 14, 
        name: "Бархатная бумага Флок Бирюзовый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/14. Бархатная бумага Флок Бирюзовый.jpg", 
        description: "Свежий бирюзовый цвет с бархатной текстурой. Создает морскую и летнюю атмосферу.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Бирюзовый"],
        status: "in-stock"
    },
    { 
        id: 15, 
        name: "Бархатная бумага Флок Салатовый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/15. Бархатная бумага Флок Салатовый.jpg", 
        description: "Яркий салатовый оттенок с бархатной текстурой. Добавляет свежести и энергии в проекты.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Салатовый"],
        status: "in-stock"
    },
    { 
        id: 16, 
        name: "Бархатная бумага Флок Сиреневый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/16. Бархатная бумага Флок Сиреневый.jpg", 
        description: "Нежный сиреневый цвет с бархатной текстурой. Создает романтичное и загадочное настроение.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Сиреневый"],
        status: "in-stock"
    },
    { 
        id: 17, 
        name: "Бархатная бумага Флок Малиновый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/17. Бархатная бумага Флок Малиновый.jpg", 
        description: "Яркий малиновый оттенок с бархатной текстурой. Идеален для смелых и выразительных проектов.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Малиновый"],
        status: "in-stock"
    },
    { 
        id: 18, 
        name: "Бархатная бумага Флок Персиковый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/18. Бархатная бумага Флок Персиковый.jpg", 
        description: "Нежный персиковый цвет с бархатной текстурой. Создает теплую и уютную атмосферу.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Персиковый"],
        status: "in-stock"
    },
    { 
        id: 19, 
        name: "Бархатная бумага Флок Лимонный", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/19. Бархатная бумага Флок Лимонный.jpg", 
        description: "Солнечный лимонный оттенок с бархатной текстурой. Добавляет яркости и позитива.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Лимонный"],
        status: "in-stock"
    },
    { 
        id: 20, 
        name: "Бархатная бумага Флок Оливковый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/20. Бархатная бумага Флок Оливковый.jpg", 
        description: "Спокойный оливковый оттенок с бархатной текстурой. Создает природную и элегантную атмосферу.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Оливковый"],
        status: "in-stock"
    },
    { 
        id: 21, 
        name: "Бархатная бумага Флок Бронзовый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 580, 
        image: "images/products/21. Бархатная бумага Флок Бронзовый.jpg", 
        description: "Богатый бронзовый оттенок с металлическим блеском. Создает роскошный эффект.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Бронзовый"],
        status: "in-stock"
    },
    { 
        id: 22, 
        name: "Бархатная бумага Флок Медный", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 580, 
        image: "images/products/22. Бархатная бумага Флок Медный.jpg", 
        description: "Теплый медный оттенок с металлическим блеском. Добавляет винтажного шарма.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Медный"],
        status: "in-stock"
    },
    { 
        id: 23, 
        name: "Бархатная бумага Флок Пудровый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/23. Бархатная бумага Флок Пудровый.jpg", 
        description: "Нежный пудровый оттенок с бархатной текстурой. Идеален для деликатных и изысканных проектов.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Пудровый"],
        status: "in-stock"
    },
    { 
        id: 24, 
        name: "Бархатная бумага Флок Графитовый", 
        density: "230 гр/м2", 
        manufacturer: "Grafix", 
        country: "США", 
        price: 520, 
        image: "images/products/24. Бархатная бумага Флок Графитовый.jpg", 
        description: "Строгий графитовый оттенок с бархатной текстурой. Создает современный и стильный вид.", 
        texture: "Флок", 
        size: "70x100 см", 
        colors: ["Графитовый"],
        status: "in-stock"
    }
];

// Остальной JavaScript код остается без изменений...
// [Весь остальной JavaScript код из предыдущей версии]